"""initial_tables_and_constraints

Revision ID: 36ac4a675c63
Revises: 
Create Date: 2026-09-11 11:11:20.334229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ac4a675c63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('shopkeeper', 'shopper', 'counter')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_created_at'), 'idempotency_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_id'), 'idempotency_records', ['id'], unique=False)
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_city'), 'shops', ['city'], unique=False)
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=True)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=30), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_purchase', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed')", name='ck_offers_discount_type'),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'expired')", name='ck_offers_status'),
    sa.CheckConstraint('discount_value >= 0', name='ck_offers_discount_value_non_negative'),
    sa.CheckConstraint('expires_at > starts_at', name='ck_offers_expiry_after_start'),
    sa.CheckConstraint('minimum_purchase IS NULL OR minimum_purchase >= 0', name='ck_offers_minimum_purchase_non_negative'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_expires_at'), 'offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_shop_id'), 'offers', ['shop_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index('ix_offers_status_expires_at', 'offers', ['status', 'expires_at'], unique=False)
    op.create_table('points_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_points_accounts_balance_non_negative'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_accounts_id'), 'points_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_points_accounts_shop_id'), 'points_accounts', ['shop_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('shopper_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('claimed', 'redeemed', 'expired', 'cancelled')", name='ck_claims_status'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['shopper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_code'), 'claims', ['code'], unique=True)
    op.create_index(op.f('ix_claims_expires_at'), 'claims', ['expires_at'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_offer_id'), 'claims', ['offer_id'], unique=False)
    op.create_index('ix_claims_offer_status', 'claims', ['offer_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_shopper_id'), 'claims', ['shopper_id'], unique=False)
    op.create_index('ix_claims_shopper_status', 'claims', ['shopper_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_by_id', sa.Integer(), nullable=False),
    sa.Column('purchase_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_redemptions_discount_amount_non_negative'),
    sa.CheckConstraint('purchase_amount >= 0', name='ck_redemptions_purchase_amount_non_negative'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_claim_id'), 'redemptions', ['claim_id'], unique=True)
    op.create_index(op.f('ix_redemptions_id'), 'redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_redemptions_redeemed_at'), 'redemptions', ['redeemed_at'], unique=False)
    op.create_index(op.f('ix_redemptions_redeemed_by_id'), 'redemptions', ['redeemed_by_id'], unique=False)
    op.create_index(op.f('ix_redemptions_shop_id'), 'redemptions', ['shop_id'], unique=False)
    op.create_index('ix_redemptions_shop_redeemed_at', 'redemptions', ['shop_id', 'redeemed_at'], unique=False)
    op.create_table('points_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('redemption_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("transaction_type IN ('top_up', 'redemption', 'adjustment')", name='ck_points_transactions_type'),
    sa.CheckConstraint('amount != 0', name='ck_points_transactions_amount_non_zero'),
    sa.CheckConstraint('balance_after >= 0', name='ck_points_transactions_balance_after_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['points_accounts.id'], ),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_points_transactions_account_created_at', 'points_transactions', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_points_transactions_account_id'), 'points_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_created_at'), 'points_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_points_transactions_id'), 'points_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_points_transactions_redemption_id'), 'points_transactions', ['redemption_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_transaction_type'), 'points_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_transactions_transaction_type'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_redemption_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_created_at'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_account_id'), table_name='points_transactions')
    op.drop_index('ix_points_transactions_account_created_at', table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index('ix_redemptions_shop_redeemed_at', table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_shop_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_redeemed_by_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_redeemed_at'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_claim_id'), table_name='redemptions')
    op.drop_table('redemptions')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index('ix_claims_shopper_status', table_name='claims')
    op.drop_index(op.f('ix_claims_shopper_id'), table_name='claims')
    op.drop_index('ix_claims_offer_status', table_name='claims')
    op.drop_index(op.f('ix_claims_offer_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_expires_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_code'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_points_accounts_shop_id'), table_name='points_accounts')
    op.drop_index(op.f('ix_points_accounts_id'), table_name='points_accounts')
    op.drop_table('points_accounts')
    op.drop_index('ix_offers_status_expires_at', table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_expires_at'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_city'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_created_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
